version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 10   # Should be 4
  complex-logic:
    config:
      threshold: 8   # Should be 4
  file-lines:
    config:
      threshold: 600   # Should be 250
  method-complexity:
    config:
      threshold: 25   # Should be 5
  method-count:
    config:
      threshold: 30   # Should be 20
  method-lines:
    config:
      threshold: 80   # Should be 25
  nested-control-flow:
    config:
      threshold: 5
  return-statements:
    config:
      threshold: 20   # Should be 4.  (We practically disable this check)
exclude_patterns:
  - ...
