version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 10   # Should be 4
  complex-logic:
    config:
      threshold: 8   # Should be 4
  file-lines:
    config:
      threshold: 500   # Should be 250
  method-complexity:
    config:
      threshold: 15   # Should be 5
  method-count:
    config:
      threshold: 30   # Should be 20
  method-lines:
    config:
      threshold: 80   # Should be 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
exclude_patterns:
  - ...
